name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Mono
        run: sudo apt-get update && sudo apt-get install -y mono-complete gtk-sharp3
      - name: Build
        working-directory: HelloWorld
        run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GtkHelloScroll
          path: HelloWorld/GtkHelloScroll.exe HelloWorld/*.ui